//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChitralekaDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailoutTracker
    {
        public long Id { get; set; }
        public int MailoutQueueId { get; set; }
        public string IPAddress { get; set; }
        public System.DateTime OpenedOn { get; set; }
    
        public virtual MailoutQueue MailoutQueue { get; set; }
    }
}
