//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChitralekaDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id { get; set; }
        public int InvoiceId { get; set; }
        public decimal DueAmount { get; set; }
        public decimal PaidAmount { get; set; }
        public decimal BalanceAmount { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public bool IsSettled { get; set; }
        public Nullable<System.DateTime> SettleDate { get; set; }
        public string Note { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
