//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChitralekaDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cLekaDbEntityContainer : DbContext
    {
        public cLekaDbEntityContainer()
            : base("name=cLekaDbEntityContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LogType> LogType { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<MailoutType> MailoutType { get; set; }
        public virtual DbSet<Salutation> Salutation { get; set; }
        public virtual DbSet<Enquiry> Enquiry { get; set; }
        public virtual DbSet<EmailAddress> EmailAddress { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<Registration> Registration { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<AcademyCenter> AcademyCenter { get; set; }
        public virtual DbSet<Grade> Grade { get; set; }
        public virtual DbSet<Invoice> Invoice { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<Key> Key { get; set; }
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<AddressType> AddressType { get; set; }
        public virtual DbSet<ContactNumberType> ContactNumberType { get; set; }
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<Sample> Sample { get; set; }
        public virtual DbSet<PersonType> PersonType { get; set; }
        public virtual DbSet<EnquiryType> EnquiryType { get; set; }
        public virtual DbSet<PersonEmail> PersonEmail { get; set; }
        public virtual DbSet<StudentGrade> StudentGrade { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<PersonRole> PersonRole { get; set; }
        public virtual DbSet<InvoiceType> InvoiceType { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<MailoutParameter> MailoutParameter { get; set; }
        public virtual DbSet<MailoutTypeParameter> MailoutTypeParameter { get; set; }
        public virtual DbSet<MailoutQueue> MailoutQueue { get; set; }
        public virtual DbSet<MailoutQueueParameterValue> MailoutQueueParameterValue { get; set; }
        public virtual DbSet<Calendar> Calendar { get; set; }
        public virtual DbSet<EventType> EventType { get; set; }
        public virtual DbSet<CalendarDetail> CalendarDetail { get; set; }
        public virtual DbSet<MailoutTracker> MailoutTracker { get; set; }
        public virtual DbSet<SecurityType> SecurityType { get; set; }
        public virtual DbSet<SecurityCode> SecurityCode { get; set; }
    }
}
