//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChitraLeka.Other_Projects.ChitralekaDB.ChitralekaDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.DateTime> LockedOn { get; set; }
        public bool IsActive { get; set; }
        public bool IsLock { get; set; }
        public bool MustChangepassword { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
