//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChitraLeka.Other_Projects.ChitralekaDB.ChitralekaDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailoutQueueParameterValue
    {
        public int Id { get; set; }
        public int MailoutQueueId { get; set; }
        public string Value { get; set; }
        public Nullable<int> MailoutTypeParameterId { get; set; }
    
        public virtual MailoutQueue MailoutQueue { get; set; }
        public virtual MailoutTypeParameter MailoutTypeParameter { get; set; }
    }
}
