//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChitraLeka.Other_Projects.ChitralekaDB.ChitralekaDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sample
    {
        public string Venue { get; set; }
        public string Day { get; set; }
        public string Time { get; set; }
        public string Total_weeks { get; set; }
        public string Unit_Fees { get; set; }
        public string Fees { get; set; }
        public string Lookup_reference { get; set; }
        public string Registration_Date { get; set; }
        public string Grade { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Date_Of_Birth { get; set; }
        public string Age { get; set; }
        public string Telephone_1 { get; set; }
        public string Telephone_2 { get; set; }
        public string Parent_Telephone { get; set; }
        public string Email_1 { get; set; }
        public string Email_2 { get; set; }
        public string Address_1 { get; set; }
        public string Address_2 { get; set; }
        public string Town { get; set; }
        public string Postcode { get; set; }
        public string Parent_Name { get; set; }
        public string Column_23 { get; set; }
        public string Column_24 { get; set; }
        public string Column_25 { get; set; }
        public string Column_26 { get; set; }
        public string Column_27 { get; set; }
        public int Id { get; set; }
    }
}
