//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChitraLeka.Other_Projects.ChitralekaDB.ChitralekaDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityCode
    {
        public int Id { get; set; }
        public int SecurityTypeId { get; set; }
        public int PersonId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> ExpiredOn { get; set; }
        public string Code { get; set; }
    
        public virtual SecurityType SecurityType { get; set; }
        public virtual Person Person { get; set; }
    }
}
